// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ivqhXPZw7ZpT9Ojl08E9TW2bQVAr_rQ',
    appId: '1:316923369990:web:93a713295c21bc39da4187',
    messagingSenderId: '316923369990',
    projectId: 'myfoodchoice-dc7bd',
    authDomain: 'myfoodchoice-dc7bd.firebaseapp.com',
    databaseURL: 'https://myfoodchoice-dc7bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfoodchoice-dc7bd.appspot.com',
    measurementId: 'G-0ZD96GDHTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGO0NFaE8rgmVPWD7ufoiDpx8vNWj1g7Q',
    appId: '1:316923369990:android:aa679b8dc447a813da4187',
    messagingSenderId: '316923369990',
    projectId: 'myfoodchoice-dc7bd',
    databaseURL: 'https://myfoodchoice-dc7bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfoodchoice-dc7bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Nyf1oYVNpUKkMqXdFtCU1ABkvRhdS50',
    appId: '1:316923369990:ios:783bae0b383baaa9da4187',
    messagingSenderId: '316923369990',
    projectId: 'myfoodchoice-dc7bd',
    databaseURL: 'https://myfoodchoice-dc7bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfoodchoice-dc7bd.appspot.com',
    iosBundleId: 'com.example.mysmartfoodchoiceFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ivqhXPZw7ZpT9Ojl08E9TW2bQVAr_rQ',
    appId: '1:316923369990:web:a578f02fc6ce0b82da4187',
    messagingSenderId: '316923369990',
    projectId: 'myfoodchoice-dc7bd',
    authDomain: 'myfoodchoice-dc7bd.firebaseapp.com',
    databaseURL: 'https://myfoodchoice-dc7bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfoodchoice-dc7bd.appspot.com',
    measurementId: 'G-3GNJCQV52B',
  );

}